services:
  - type: web
    name: unicorn-api
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: NEO4J_URI
        value: neo4j+s://1f4d108d.databases.neo4j.io
      - key: NEO4J_USERNAME
        value: neo4j
      - key: NEO4J_PASSWORD
        value: jkorB-rHOwt9JgLzgbQjmJSg13cPcmBCxwLs7H_l0Jg
